language: python
python:
  - "3.5.1"
before_install:
  - sudo apt-get -y install libffi-dev
  - sudo apt-get -y install libpq-dev
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database app_db;' -U postgres
script:
  - python manage.py runtests
